version: "3.0"
#This file combines all the edge services and our services so that it can be deployed as a unit
services:
  opcua-simulator:
    image: "predixedge/predix-edge-opcua-simulator:1.0.9"
    hostname: "opcua-simulator"
    volumes:
      - ./config:/config
    networks:
      - predix-edge-broker_net
    ports:
      - 4334:4334
    #entrypoint: ["sh", "-c", "sleep 500000"]
  opcua:
    image: "dtr.predix.io/predix-edge/protocol-adapter-opcua:amd64-1.1.0"
    environment:
      config: "/config/config-opcua.json"
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      - predix-edge-broker_net
  cloud_gateway:
    image: "dtr.predix.io/predix-edge/cloud-gateway:amd64-1.1.0"
    environment:
      config: "/config/config-cloud-gateway.json"
    volumes:
      - ./config:/config
      - ./data:/data
      - ./data:/edge-agent
    networks:
      - predix-edge-broker_net
  edge-app:
    image: "predixedge/predix-edge-sample-scaler-go:1.0.2"
    environment:
      CLIENT_ID: "go-simple"
      BROKER: "predix-edge-broker:1883"
      SUB_TOPIC: "app_data"
      PUB_TOPIC: "timeseries_data"
      TAG_NAME: "My.App.DOUBLE1"
    volumes:
      - ./config:/config
      - ./data:/data
      - ./data:/edge-agent
    environment:
      CLIENT_ID: "go-simple"
      BROKER: "predix-edge-broker:1883"
      PUB_TOPIC: "timeseries_data"
      SUB_TOPIC: "app_data"
      TAG_NAME: "My.App.DOUBLE1"
    networks:
      - predix-edge-broker_net
    #entrypoint: ["sh", "-c", "sleep 500000"]
networks:
  predix-edge-broker_net:
    external: true
